import React from 'react';
import {AbsoluteFill, Easing, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame} from 'remotion';

const W=1920,H=1080,SW=1286,SH=972;
const RED='#c9152d',INK='#151515',PAPER='#f7f7f5';
const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
const ease=Easing.bezier(.16,1,.3,1);
const fontCss=`@font-face{font-family:ManropeLocal;src:url('${staticFile('manrope-latin.woff2')}') format('woff2');font-weight:200 800;font-style:normal;font-display:swap;}`;

type Cam={cx:number;cy:number;zoom:number};
const camPos=(c:Cam)=>({left:W/2-c.cx*c.zoom,top:H/2-c.cy*c.zoom});
const map=(x:number,y:number,c:Cam)=>{const p=camPos(c);return{x:p.left+x*c.zoom,y:p.top+y*c.zoom}};
const Shell:React.FC<{children:React.ReactNode;background?:string;color?:string}>=({children,background=PAPER,color=INK})=><AbsoluteFill style={{background,color,fontFamily:'ManropeLocal, Segoe UI, sans-serif',overflow:'hidden'}}><style>{fontCss}</style>{children}</AbsoluteFill>;
const Source:React.FC<{src:'Pic1.png'|'Pic2.png'|'Pic3.png'|'Pic4.png';camera:Cam;opacity?:number}>=({src,camera,opacity=1})=>{const p=camPos(camera);return <div style={{position:'absolute',left:p.left,top:p.top,width:SW,height:SH,scale:camera.zoom,transformOrigin:'0 0',opacity}}><Img src={staticFile(src)} style={{width:SW,height:SH,display:'block'}}/></div>};
const Cursor:React.FC<{x:number;y:number;down?:number}>=({x,y,down=0})=><div style={{position:'absolute',left:x,top:y,width:34,height:46,scale:1-down*.1,transformOrigin:'3px 3px',filter:'drop-shadow(0 5px 7px #0005)'}}><svg viewBox="0 0 28 38"><path d="M2 2l22 21-11 1 6 11-5 2-6-11-7 8z" fill="white" stroke="#111" strokeWidth="2"/></svg></div>;
const Ring:React.FC<{x:number;y:number;w:number;h:number;camera:Cam;opacity?:number}>=({x,y,w,h,camera,opacity=1})=>{const p=map(x,y,camera);return <div style={{position:'absolute',left:p.x,top:p.y,width:w*camera.zoom,height:h*camera.zoom,border:`2px solid ${RED}`,borderRadius:12,boxSizing:'border-box',boxShadow:'0 0 0 6px rgba(201,21,45,.08)',opacity}}/>};
const Editorial:React.FC<{kicker:string;title:string;body?:string;side?:'left'|'right';dark?:boolean}>=({kicker,title,body,side='left',dark=false})=><div style={{position:'absolute',top:66,[side]:70,width:520,pointerEvents:'none',textShadow:dark?'0 2px 14px #000':''}}><div style={{fontSize:17,fontWeight:800,letterSpacing:2.5,color:RED}}>{kicker}</div><div style={{fontSize:38,fontWeight:800,lineHeight:1.06,letterSpacing:-1.6,marginTop:8,color:dark?'white':INK}}>{title}</div>{body&&<div style={{fontSize:20,lineHeight:1.45,marginTop:11,color:dark?'#ddd':'#666'}}>{body}</div>}</div>;

const S1=()=>{const f=useCurrentFrame();const s=spring({frame:f-6,fps:30,config:{damping:22,stiffness:82}});return <Shell background="#fff"><div style={{margin:'auto',textAlign:'center',opacity:s,translate:`0 ${(1-s)*22}px`}}><Img src={staticFile('Logo.png')} style={{width:128,height:128,objectFit:'contain'}}/><div style={{fontSize:82,fontWeight:800,letterSpacing:-4.2,marginTop:22}}>GetVideosLocally</div><div style={{fontSize:29,color:'#666',marginTop:14}}>Paste a link. Choose your quality. Keep the file.</div></div></Shell>};

const S2=()=>{const f=useCurrentFrame();const t=interpolate(f,[0,105],[0,1],{...clamp,easing:ease});const camera={cx:interpolate(t,[0,1],[643,286]),cy:interpolate(t,[0,1],[486,468]),zoom:interpolate(t,[0,1],[1.12,2.04])};const a=map(1040,770,camera),b=map(304,468,camera);const m=interpolate(f,[48,92],[0,1],{...clamp,easing:ease});return <Shell background="#171717"><Source src="Pic2.png" camera={camera}/><Editorial kicker="01  PASTE" title="Start with the link." body="The camera isolates the real URL control in place." dark/><Ring x={35} y={441} w={505} h={56} camera={camera} opacity={interpolate(f,[72,94],[0,1],clamp)}/><Cursor x={interpolate(m,[0,1],[a.x,b.x])} y={interpolate(m,[0,1],[a.y,b.y])}/></Shell>};

const S3=()=>{const f=useCurrentFrame();const t=interpolate(f,[0,110],[0,1],{...clamp,easing:ease});const camera={cx:interpolate(t,[0,1],[286,310]),cy:interpolate(t,[0,1],[468,582]),zoom:interpolate(t,[0,1],[2.04,2.12])};const a=map(185,579,camera),b=map(420,579,camera);const m=interpolate(f,[44,92],[0,1],{...clamp,easing:ease});return <Shell background="#171717"><Source src="Pic2.png" camera={camera}/><Editorial kicker="02  CHOOSE" title="Format. Then quality." body="One continuous camera move keeps the controls spatially connected." side="right" dark/><Ring x={36} y={553} w={244} h={55} camera={camera} opacity={1-m}/><Ring x={295} y={553} w={242} h={55} camera={camera} opacity={m}/><Cursor x={interpolate(m,[0,1],[a.x,b.x])} y={interpolate(m,[0,1],[a.y,b.y])}/></Shell>};

const S4=()=>{const f=useCurrentFrame();const camera={cx:286,cy:714,zoom:2.08};const c=map(300,714,camera);const click=interpolate(f,[40,47,55],[0,1,0],clamp);const grow=interpolate(f,[56,104],[0,1],{...clamp,easing:ease});return <Shell background="#171717"><Source src="Pic2.png" camera={camera}/><Editorial kicker="03  DOWNLOAD" title="One primary action." body="The cursor lands on the authentic Download Now control." dark/><Ring x={35} y={686} w={505} h={59} camera={camera}/><Cursor x={c.x} y={c.y} down={click}/><div style={{position:'absolute',left:map(35,686,camera).x,top:map(35,686,camera).y,width:505*camera.zoom,height:59*camera.zoom,background:RED,borderRadius:12,scale:1+grow*22,opacity:grow,transformOrigin:'50% 50%'}}/></Shell>};

const S5=()=>{const f=useCurrentFrame();const reveal=interpolate(f,[0,18],[0,1],clamp);const t=interpolate(f,[18,145],[0,1],{...clamp,easing:ease});const camera={cx:interpolate(t,[0,1],[643,925]),cy:interpolate(t,[0,1],[486,392]),zoom:interpolate(t,[0,1],[1.1,1.62])};return <Shell background={RED}><Source src="Pic1.png" camera={camera} opacity={reveal}/><Editorial kicker="04  PROGRESS" title="See the download happen." body="The real captured progress row becomes the entire point of the frame."/><Ring x={615} y={323} w={624} h={175} camera={camera} opacity={interpolate(f,[48,70],[0,1],clamp)}/></Shell>};

const S6=()=>{const f=useCurrentFrame();const items=['MP4 · up to 8K','MKV · WEBM · MOV','MP3 · WAV · FLAC','M4A · OPUS','1000+ supported sites'];return <Shell background="#fff"><div style={{display:'flex',height:'100%',alignItems:'center',padding:'0 185px',gap:130}}><div style={{width:800}}><div style={{fontSize:19,fontWeight:800,letterSpacing:2.8,color:RED}}>FLEXIBLE BY DESIGN</div><div style={{fontSize:70,fontWeight:800,letterSpacing:-3.5,lineHeight:1.03,marginTop:18}}>Your format.<br/>Your quality.</div><div style={{fontSize:23,color:'#666',lineHeight:1.5,marginTop:24}}>An editorial capability beat — deliberately not presented as application UI.</div></div><div style={{height:510,width:600,overflow:'hidden',maskImage:'linear-gradient(transparent,black 18%,black 82%,transparent)'}}><div style={{translate:`0 ${80-(f*2.05)%490}px`}}>{[...items,...items,...items].map((x,i)=><div key={i} style={{height:94,display:'flex',alignItems:'center',fontSize:29,fontWeight:750,borderBottom:'1px solid #ddd'}}><span style={{width:11,height:11,borderRadius:99,background:RED,marginRight:22}}/>{x}</div>)}</div></div></div></Shell>};

const S7=()=>{const f=useCurrentFrame();const t=interpolate(f,[0,130],[0,1],{...clamp,easing:ease});const camera={cx:interpolate(t,[0,1],[643,350]),cy:interpolate(t,[0,1],[500,410]),zoom:interpolate(t,[0,1],[1.08,1.72])};const a=map(1080,700,camera),b=map(382,427,camera);const m=interpolate(f,[58,112],[0,1],{...clamp,easing:ease});return <Shell background="#0d1838"><Source src="Pic3.png" camera={camera}/><Editorial kicker="05  HISTORY" title="Your files stay actionable." body="The camera reframes a real history card and approaches its real folder control." side="right" dark/><Ring x={12} y={358} w={402} h={185} camera={camera} opacity={interpolate(f,[75,98],[0,1],clamp)}/><Cursor x={interpolate(m,[0,1],[a.x,b.x])} y={interpolate(m,[0,1],[a.y,b.y])}/></Shell>};

const S8=()=>{const f=useCurrentFrame();const cards=[['8K','quality support',145,145],['1000+','supported sites',1435,165],['Free','no subscription',180,780],['Local','desktop workflow',1420,765]] as const;return <Shell background="#f5f5f2"><div style={{margin:'auto',textAlign:'center',width:930}}><div style={{fontSize:70,fontWeight:800,letterSpacing:-3.6,lineHeight:1.04}}>High quality.<br/>Without the paywall.</div><div style={{fontSize:24,color:'#666',marginTop:20}}>Download, process and keep control of your files.</div></div>{cards.map((c,i)=>{const s=spring({frame:f-i*8,fps:30,config:{damping:18,stiffness:82}});return <div key={c[0]} style={{position:'absolute',left:c[2]+(i%2?1:-1)*(1-s)*80,top:c[3]+(i<2?-1:1)*(1-s)*60,width:310,height:142,padding:'25px 27px',boxSizing:'border-box',border:'1px solid #ddd',borderRadius:24,background:'#fff',boxShadow:'0 18px 50px #00000012',opacity:s,scale:.94+s*.06}}><div style={{fontSize:45,fontWeight:800,color:RED,lineHeight:1}}>{c[0]}</div><div style={{fontSize:20,color:'#666',marginTop:10}}>{c[1]}</div></div>})}</Shell>};

const S9=()=>{const f=useCurrentFrame();const s=spring({frame:f-4,fps:30,config:{damping:24,stiffness:78}});return <Shell background="#090909" color="#fff"><div style={{margin:'auto',textAlign:'center',opacity:s,scale:.97+s*.03}}><Img src={staticFile('Logo.png')} style={{width:148,height:148,objectFit:'contain'}}/><div style={{fontSize:60,fontWeight:800,letterSpacing:-2.8,marginTop:24}}>GetVideosLocally</div><div style={{fontSize:25,color:'#aaa',marginTop:10}}>Free. Local. Up to 8K.</div></div></Shell>};

export const ProductDemo:React.FC=()=> <AbsoluteFill><Sequence from={0} durationInFrames={105}><S1/></Sequence><Sequence from={105} durationInFrames={165}><S2/></Sequence><Sequence from={270} durationInFrames={135}><S3/></Sequence><Sequence from={405} durationInFrames={120}><S4/></Sequence><Sequence from={525} durationInFrames={180}><S5/></Sequence><Sequence from={705} durationInFrames={165}><S6/></Sequence><Sequence from={870} durationInFrames={180}><S7/></Sequence><Sequence from={1050} durationInFrames={180}><S8/></Sequence><Sequence from={1230} durationInFrames={120}><S9/></Sequence></AbsoluteFill>;
